language: python
python:
  - "3.5"
sudo: required
install:
  - pip install -r test-requirements.txt
script:
  - flake8 lib reactive
  - flake8 --ignore=E402 unit_tests
  - sudo sh -c ". '$VIRTUAL_ENV/bin/activate'; exec ostestr"
