options:
  bypassed_checks:
    type: string
    description: Consciously bypass some of the configuration checks.
    default: none
  cgroup_slice_size:
    type: string
    description: The size of the various control group memory slices.
    default: system:4 user:4 storpool:1 kernel:10
  handle_lxc:
    type: boolean
    description: Specify whether LXC containers should be searched for applications.
    default: false
  storpool_charm_log_file:
    type: string
    description: The full path to a file for logging additional diagnostics.
    default: /dev/null
  storpool_conf:
    type: string
    description: The contents of the /etc/storpool.conf file.
    default:
  storpool_debug:
    type: string
    description: An optional comma-separated list of debug tags or 'ALL'
    default:
  storpool_openstack_version:
    type: string
    description: The version of the StorPool OpenStack integration Ubuntu packages to install.
    default:
  storpool_openstack_install:
    type: boolean
    description: Is this charm responsible for installing the StorPool OpenStack integration?
    default: true
  storpool_repo_url:
    type: string
    description: The location of the StorPool APT repository.
    default:
  storpool_version:
    type: string
    description: The version of the StorPool Ubuntu packages to install.
    default:
